/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import config.StaticInitConfig;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author boluo
 */
public class EnemyThreatAndTargetInitPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnemyThreatAndTargetInitPanel
     */
    public EnemyThreatAndTargetInitPanel() {
        initComponents();
//        initSpinnerValue();
    }

//    private void initSpinnerValue() {
//        this.jSpinner1.setModel(new SpinnerNumberModel(StaticInitConfig.ENEMY_UAV_NUM, StaticInitConfig.MIN_SPINNER_VALUE, StaticInitConfig.MAX_SPINNER_VALUE, StaticInitConfig.STEP_SIZE_OF_SPINNER));
//        this.jSpinner4.setModel(new SpinnerNumberModel(StaticInitConfig.THREAT_NUM, StaticInitConfig.MIN_SPINNER_VALUE, StaticInitConfig.MAX_SPINNER_VALUE, StaticInitConfig.STEP_SIZE_OF_SPINNER));
//        this.jSpinner5.setModel(new SpinnerNumberModel(StaticInitConfig.THREAT_NUM, StaticInitConfig.MIN_SPINNER_VALUE, StaticInitConfig.MAX_SPINNER_VALUE, StaticInitConfig.STEP_SIZE_OF_SPINNER));
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(180, 100));

        jSplitPane1.setDividerLocation(50);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jToolBar1.setRollover(true);

        jLabel1.setText("静态威胁数量");
        jToolBar1.add(jLabel1);

        jSpinner1.setMaximumSize(new java.awt.Dimension(82, 32767));
        jSpinner1.setMinimumSize(new java.awt.Dimension(82, 28));
        jSpinner1.setPreferredSize(new java.awt.Dimension(82, 28));
        jToolBar1.add(jSpinner1);

        jSplitPane1.setTopComponent(jToolBar1);

        jToolBar2.setRollover(true);

        jLabel2.setText("动态威胁数量");
        jToolBar2.add(jLabel2);

        jSpinner2.setMaximumSize(new java.awt.Dimension(82, 32767));
        jSpinner2.setMinimumSize(new java.awt.Dimension(82, 28));
        jSpinner2.setPreferredSize(new java.awt.Dimension(82, 28));
        jToolBar2.add(jSpinner2);

        jSplitPane1.setRightComponent(jToolBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
