/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import config.StaticInitConfig;
import java.awt.event.ActionEvent;

/**
 *
 * @author boluo
 */
public class ViewSettingPanel extends javax.swing.JPanel {
    private static org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(ViewSettingPanel.class);

    /**
     * Creates new form ViewSettingPanel
     */
    public ViewSettingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSplitPane3 = new javax.swing.JSplitPane();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(320, 80));
        setMinimumSize(new java.awt.Dimension(320, 80));
        setPreferredSize(new java.awt.Dimension(320, 80));

        jSplitPane1.setDividerLocation(160);
        jSplitPane1.setDividerSize(1);

        jSplitPane2.setDividerLocation(80);
        jSplitPane2.setDividerSize(1);

        jButton1.setText("显示障碍");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jSplitPane2.setLeftComponent(jButton1);

        jButton2.setText("显示威胁");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jSplitPane2.setRightComponent(jButton2);

        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane3.setDividerLocation(80);
        jSplitPane3.setDividerSize(1);
        jSplitPane3.setMaximumSize(new java.awt.Dimension(160, 80));
        jSplitPane3.setMinimumSize(new java.awt.Dimension(160, 80));
        jSplitPane3.setPreferredSize(new java.awt.Dimension(160, 80));

        jButton3.setText("显示目标");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jSplitPane3.setLeftComponent(jButton3);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jSplitPane3.setRightComponent(jButton4);

        jSplitPane1.setRightComponent(jSplitPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionCommand(ActionEvent evt) {
        String action_command = evt.getActionCommand();
        logger.debug(action_command);
        if (action_command.equals(StaticInitConfig.VIEW_OBSTACLE_ACTION_COMMAND)) {
            StaticInitConfig.VIEW_ENEMY_UAV = !StaticInitConfig.VIEW_ENEMY_UAV;
        } else if (action_command.equals(StaticInitConfig.VIEW_THREAT_ACTION_COMMAND)) {
            StaticInitConfig.VIEW_THREAT = !StaticInitConfig.VIEW_THREAT;
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButtonActionCommand(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButtonActionCommand(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButtonActionCommand(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    // End of variables declaration//GEN-END:variables
}
